### ISSUE TITLE
Issue with "run" command + Hosting

### ISSUE THREAD

**Issue by samip5** [jbelien/php-github-webhook#7]
This does not work, it only gives me HTTP error 500's. :-1:

**Comment by jbelien** [comment]
Hello @samip5 ,

Could you give me more details about your issue ?
Could you send me a copy of your config file ?
Some lines from the PHP error log ?

Thanks.

**Comment by samip5** [comment]
Hello, thank you for the quick reply.

Apperently the error has to do with me trying to cd out of the application folder, but how would I manage to do git pull then if I can't cd out?

`Exit Code: 2(Misuse of shell builtins)`

My config/application/config.php:
```
<?php

return [
    'token' => '<nope>',
    'endpoints' => [
        [
            'repository' => 'samip5/<private-repo>',
            'branch' => 'master',
            'run' => 'cd /var/www/9/<username>/sites/<my-domain>/tiko/develop/ && git pull -f',
        ],
    ],
];
```

**Comment by jbelien** [comment]
I would suggest to only put one single command in `run` parameter and put all the commands you need to run in a shell script.

Something like :
```php
<?php

return [
    'token' => '<nope>',
    'endpoints' => [
        [
            'repository' => 'samip5/<private-repo>',
            'branch' => 'master',
            'run' => 'sh mytask.sh',
        ],
    ],
];
```

`mytask.sh` :
```shell
#!/bin/sh

cd /var/www/9/<username>/sites/<my-domain>/tiko/develop/ && \
git pull -f
```

**Comment by samip5** [comment]
Okey, I got that part working now.

How would I run the app without using the php dev server?

Rewrite rules would be much appreciated and I would only want the webhook endpoint to be accessable.

**Comment by jbelien** [comment]
I provide the source code, not the hosting :)

You have to host your application somewhere using [Apache](https://httpd.apache.org/) (for instance) with PHP enabled of course and make your [`DocumentRoot`](https://httpd.apache.org/docs/2.4/fr/mod/core.html#documentroot) point to `public/` folder of this tool.
You can then configure all the rewrite rules you want !

**Comment by samip5** [comment]
Okey fair enough, but my error now is `Cannot POST https://<domain>/github/webhook`  :(

**Comment by jbelien** [comment]
Where do you have this error ?

**Comment by samip5** [comment]
It shows up in Github repo-specifc webhook page, in the response tab.

**Comment by jbelien** [comment]
Could you show me your Apache configuration ?
And the full debug message from GitHub webhook ?

**Comment by samip5** [comment]
What do you mean by full debug message exactly?

PHP is being executed in a web backend with: `#!/usr/bin/php-cgi7.2` and that's inside a script file.

I have a symbolic link from `<domain>/github` to git repo public folder.

**Comment by jbelien** [comment]
What happen when you try to access `https://<domain>/github/webhook` in a browser ?
You should have a blank page with a `405 Method Not Allowed` error code !

I think your issue is caused by your configuration ... If you don't have the blank page with a `405 Method Not Allowed`, your "web server" configuration is not correct !
Usually, you run your PHP application behind a web server like Apache or NGINX ...

**Comment by samip5** [comment]
> What happen when you try to access `https://<domain>/github/webhook` in a browser ?
> You should have a blank page with a `405 Method Not Allowed` error code !
> 
> I think your issue is caused by your configuration ... If you don't have the blank page with a `405 Method Not Allowed`, your "web server" configuration is not correct !
> Usually, you run your PHP application behind a web server like Apache or NGINX ...

It is behind a web backend running Apache, with PHP7.2-CGI and I get error `cannot GET <url>` when browsing to the page.

**Comment by jbelien** [comment]
Then, as I said, your Apache configuration is not correct. :)
You have to set your `DocumentRoot` on `public/` folder !

**Comment by samip5** [comment]
> Then, as I said, your Apache configuration is not correct. :)
> You have to set your `DocumentRoot` on `public/` folder !

No root privileges, that's why I can't set DocumentRoot and I'm trying to get it to work with the usage of rewrite. However, I have only rewritten to `public/`so I don't really know if the files from `vendor` folder are able to load.

**Comment by jbelien** [comment]
I get it could work, the most important part is to be sure, the "root" is the `public/` folder **AND** that the `public/.htacess` is "executed" (with [`AllowOverride`](https://httpd.apache.org/docs/2.4/fr/mod/core.html#allowoverride)).

Sorry I can't help you more ...

**Comment by samip5** [comment]
Issue is resolved by just using the development PHP server to serve it from and proxing it though Apache.

Well not really **resolved**, but close enough for me.
